FROM 686901913580.dkr.ecr.eu-west-1.amazonaws.com/lambda-gdal-runner:latest

ARG LAMBDA_TASK_ROOT="/var/task"
ARG PYTHONPATH="${LAMBDA_TASK_ROOT}:${PYTHONPATH}:/usr/local/lib/python3/dist-packages"

COPY ./src ${LAMBDA_TASK_ROOT}/src

COPY .env ${LAMBDA_TASK_ROOT}
RUN ls -l ${LAMBDA_TASK_ROOT}/.env
RUN . ${LAMBDA_TASK_ROOT}/.env

RUN ls -l /usr/bin/which
RUN /usr/bin/which python
RUN python -v
RUN echo "PYTHONPATH: ${PYTHONPATH}."
RUN echo "PATH: ${PATH}."
RUN echo "LAMBDA_TASK_ROOT: ${LAMBDA_TASK_ROOT}."
RUN ls -l ${LAMBDA_TASK_ROOT}
RUN ls -ld ${LAMBDA_TASK_ROOT}
RUN python -c "import sys; print(sys.path)"
RUN python -c "import osgeo"
RUN python -c "import rasterio"
RUN python -c "import awslambdaric"
RUN python -m pip list
RUN python -m pip freeze
RUN df -h

RUN echo "$(date "+%Y%m%d_%H%M%S")" > ${LAMBDA_TASK_ROOT}/buildtime.txt
RUN python -m pip freeze > ${LAMBDA_TASK_ROOT}/pythonpackages.txt

CMD [ "src.surferdtm_prediction_api.app.lambda_handler" ]
