FROM python:3.11

WORKDIR /code

RUN which python
RUN python --version
RUN python -m pip install --no-cache-dir fastapi uvicorn loguru

RUN useradd -m -u 1000 user

USER user

ENV HOME=/home/user \
	PATH=/home/user/.local/bin:$PATH

WORKDIR $HOME/app

RUN ls -l ${HOME}/
COPY --chown=user src $HOME/app/src
COPY --chown=user static $HOME/app/static

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "7860"]