FROM localhost/samgis-base-aws-lambda:latest

# Include global arg in this stage of the build
ARG LAMBDA_TASK_ROOT="/var/task"
ARG PYTHONPATH="${LAMBDA_TASK_ROOT}:${PYTHONPATH}:/usr/local/lib/python3/dist-packages"
ENV VIRTUAL_ENV=${LAMBDA_TASK_ROOT}/.venv \
    PATH="${LAMBDA_TASK_ROOT}/.venv/bin:$PATH"
ENV IS_AWS_LAMBDA="True"

# Set working directory to function root directory
WORKDIR ${LAMBDA_TASK_ROOT}
COPY ./samgis ${LAMBDA_TASK_ROOT}/samgis
COPY ./wrappers ${LAMBDA_TASK_ROOT}/wrappers

RUN ls -l /usr/bin/which
RUN /usr/bin/which python
RUN python -v
RUN echo "PYTHONPATH: ${PYTHONPATH}."
RUN echo "PATH: ${PATH}."
RUN echo "LAMBDA_TASK_ROOT: ${LAMBDA_TASK_ROOT}."
RUN ls -l ${LAMBDA_TASK_ROOT}
RUN ls -ld ${LAMBDA_TASK_ROOT}
RUN ls -l ${LAMBDA_TASK_ROOT}/machine_learning_models
RUN python -c "import sys; print(sys.path)"
RUN python -c "import awslambdaric"
RUN python -c "import cv2"
RUN python -c "import geopandas"
RUN python -c "import onnxruntime"
RUN python -c "import rasterio"
RUN df -h
RUN ls -l /lambda-entrypoint.sh
RUN ls -l ${LAMBDA_TASK_ROOT}/samgis/
RUN ls -l ${LAMBDA_TASK_ROOT}/wrappers/

ENTRYPOINT  ["/lambda-entrypoint.sh"]
CMD [ "wrappers.lambda_wrapper.lambda_handler" ]
